on:
  schedule:
    - cron: '0 14,15 * * *'

name: Mirror workflow

jobs:
  hello_job:
    name: Hello job
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "The other workflow should now have triggered."